#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $TITAJIUM_REPO == "TITANIUM_USERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $TITANIUM_REPO == "TITANIUM_USERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $HELL_REPO =~ $regex ]]
    then
        if [[ $TITANIUM_REPO_BRANCH ]]
        then
            echo "${TITANIUM_REPO}/archive/${TITANIUM_REPO_BRANCH}.zip"
        else
            echo "${HELL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="mytitaniumbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "  • Starting TITANIUMBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m TITANIUMBot
}

start_bot
